// Data sourced from results/full_eval.json — real pipeline output

window.DATA = {
  variants: {
    A: { id: 'A', name: 'ROI-Led', full: 'Variant A \u2014 ROI-led, analytical',
         hook: '\u201c3 recurring syncs. 30 minutes each. 8 people on every call.\u201d',
         color: '#4361ee', colorInk: '#1e3a8a', colorSoft: '#e0e7ff',
         mean: 6.25, ci: [5.98, 6.55] },
    B: { id: 'B', name: 'Story-Driven', full: 'Variant B \u2014 Story-driven, tension-first',
         hook: '\u201cOur last \u0022quick sync\u0022 took 47 minutes.\u201d',
         color: '#f72585', colorInk: '#9d174d', colorSoft: '#fce7f3',
         mean: 6.06, ci: [5.65, 6.42] },
    C: { id: 'C', name: 'Social Proof', full: 'Variant C \u2014 Social proof-led, peer-validation',
         hook: '\u201cLinear, Vercel, Lattice \u2014 all made the same change last year.\u201d',
         color: '#06d6a0', colorInk: '#065f46', colorSoft: '#d1fae5',
         mean: 7.15, ci: [6.99, 7.32] },
  },
  personas: [
    { id: 'alex',   name: 'Alex',   title: 'VP Engineering',  weight: 30, profile: 'ROI-focused, high skepticism',   accent: '#6366f1' },
    { id: 'jordan', name: 'Jordan', title: 'Head of Remote',  weight: 25, profile: 'Trust-focused, peer-driven',     accent: '#ec4899' },
    { id: 'sam',    name: 'Sam',    title: 'Founder / CEO',   weight: 20, profile: 'Identity-driven, early-stage',   accent: '#f59e0b' },
    { id: 'taylor', name: 'Taylor', title: 'Senior Engineer', weight: 25, profile: 'Pain-driven, tool influencer',   accent: '#10b981' },
  ],
  // persona x variant scores (0-10) — from per_persona_scores
  scores: {
    alex:   { A: 6.8, B: 5.8, C: 7.0 },
    jordan: { A: 7.8, B: 7.2, C: 7.8 },
    sam:    { A: 4.8, B: 5.6, C: 7.0 },
    taylor: { A: 5.2, B: 5.6, C: 6.8 },
  },
  // element attribution (-100 to +100) — from per_variant_element_attribution
  attribution: {
    A: [
      { id: 'A_E1_hook',     label: 'Opening math hook',        score:  +95 },
      { id: 'A_E2_evidence', label: '720-hour pain data',       score:  +85 },
      { id: 'A_E3_outcomes', label: 'Before/after bullets',     score:  +50 },
      { id: 'A_E4_proof',    label: '\u201c9 hrs reclaimed\u201d claim', score:  +25 },
      { id: 'A_E5_cta',      label: 'Free trial CTA',           score:   +5 },
      { id: 'A_E6_hashtags', label: 'Hashtags',                  score:    0 },
    ],
    B: [
      { id: 'B_E1_hook',         label: '\u201c47-minute sync\u201d opener',     score: +100 },
      { id: 'B_E2_scenario',     label: 'Meeting spiral story',       score: +100 },
      { id: 'B_E3_pivot',        label: '\u201cShould\'ve been 90s video\u201d', score: +100 },
      { id: 'B_E4_mechanism',    label: 'Async workflow pitch',       score:  +45 },
      { id: 'B_E5_social_proof', label: '\u201c14,000 teams\u201d stat',        score:  -50 },
      { id: 'B_E6_cta',          label: 'Link in comments',           score:    0 },
    ],
    C: [
      { id: 'C_E1_hook',      label: 'Named peer companies',              score: +100 },
      { id: 'C_E2_reveal',    label: '\u201cStopped defaulting to syncs\u201d', score: +100 },
      { id: 'C_E3_pattern',   label: '90s video replaces 30m sync',       score: +100 },
      { id: 'C_E4_testimony', label: '11\u21924 syncs personal proof',    score: +100 },
      { id: 'C_E5_reframe',   label: '\u201cWhat replaces meetings?\u201d',     score: +100 },
      { id: 'C_E6_cta',       label: 'Link in comments',                  score:  -10 },
      { id: 'C_E7_hashtags',  label: 'Hashtags',                           score:    0 },
    ],
  },
  minimalPairs: {
    skepticism: {
      title: 'Skeptical vs. trusting audience',
      explain: "Same persona (Alex, VP Eng), same ad (Variant B) \u2014 but one version is highly skeptical of marketing claims, the other is open. What breaks?",
      low: 'Trusting', high: 'Skeptical',
      actionLow: 7.0, actionHigh: 4.8,
      biggestElement: '\u201c14,000 teams\u201d stat',
      biggestDelta: -160,
      elements: [
        { label: '\u201c47-minute sync\u201d opener',     low: +100, high: +100 },
        { label: 'Meeting spiral story',       low: +100, high: +100 },
        { label: '\u201cShould\'ve been 90s video\u201d', low: +100, high:  +60 },
        { label: 'Async workflow pitch',       low:  +80, high:    0 },
        { label: '\u201c14,000 teams\u201d stat',        low:  +60, high: -100 },
        { label: 'Link in comments',           low:    0, high:    0 },
      ],
      insight: 'When skepticism goes up, the \u201c14,000 teams\u201d stat flips from +60 to \u2212100 \u2014 a 160-point swing. The hook and story are skepticism-proof. The social proof claim is not.',
    },
    pain: {
      title: 'Aware vs. unaware of the problem',
      explain: "Same persona (Alex, VP Eng), same ad (Variant B) \u2014 but one version acutely feels the meeting-overload pain, the other hasn\u2019t noticed yet. What changes?",
      low: 'Unaware', high: 'Aware',
      actionLow: 5.0, actionHigh: 6.2,
      biggestElement: '\u201cShould\'ve been 90s video\u201d',
      biggestDelta: +40,
      elements: [
        { label: '\u201c47-minute sync\u201d opener',     low: +100, high: +100 },
        { label: 'Meeting spiral story',       low: +100, high: +100 },
        { label: '\u201cShould\'ve been 90s video\u201d', low:  +60, high: +100 },
        { label: 'Async workflow pitch',       low:    0, high:    0 },
        { label: '\u201c14,000 teams\u201d stat',        low: -100, high: -100 },
        { label: 'Link in comments',           low:    0, high:    0 },
      ],
      insight: 'The story hook works whether or not the reader feels the pain. But the product pivot (\u201cshould\u2019ve been a 90-second video\u201d) only converts when the reader has actively experienced meeting overload \u2014 otherwise it reads as someone else\u2019s problem.',
    },
  },
  diagnostics: {
    selfConsistency: { mean: 0.72, label: 'Krippendorff\u2019s \u03b1 \u00b7 ordinal' },
    personaDiff: { mean: 0.68, collapsed: '15/19', label: 'mean between-persona variance' },
    positionBias: { flagged: 1, detail: 'C_E2_reveal: \u03c1=\u22120.46, p=0.039', label: 'Spearman \u03c1 < 0.3 threshold' },
    closecall: { value: false, label: 'MDE = 0.5, Kohavi et al. 2020' },
  },
  cost: { total: 0.04, calls: 60, prompt_tokens: 193665, cached_tokens: 139904, completion_tokens: 39517, cacheHit: 0.72 },
  runs: 5,
  effect: { cohensD: 0.90, label: 'Large' },
};
